apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  user: <username> #create a separate github user for CI/CD and encode it with base64 | example : echo -n "username" | base64
  email: <email> #create a separate github email for CI/CD and encode it with base64 | example : echo -n "email" | base64
  token: <token> #create a separate Personal github token for CI/CD and encode it with base64 | example : echo -n "personal-github-token" | base64
  secret: <trigger-secret> #create a password (random) : webhook's secrets to trigger event source. | example : echo -n "password" | base64 
