apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-test-manifest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:saroj-2052/node-test-manifest.git
    targetRevision: HEAD
    path: <> #eg:-path of the manifest file to update:    manifest/node-test.yaml
  destination:
    namespace: <> #eg:- namespace 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true